# LayerWiseSubset data curation with MeSO optimizer
method: LayerWiseSubset
finetuning: MeSO
learning_rate: 1.00e-05

scoring:
  method: compress
  compression: normal-512*512
optimizer:
  compression: normal-512*512
