defaults:
  - /eval@eval: nll
  - /dataset@dataset: qa
  - /dataset/sources@dataset: squad_qa
  - _self_

eval:
  eval_steps: 50
dataset:
  split: validation
  seq_len: 64
  doc_chunk_seq_len: 256
  num_chunks_per_doc: 2
  num_workers: 0
  batch_size: 32
