# GlobalSubset data curation with MeSO optimizer (exact scoring)
method: GlobalSubset
subset_mode: one_pass
scoring:
  method: reduced_ghost
finetuning: MeSO
learning_rate: 1.00e-05

optimizer:
  compression: normal-512*512
