defaults:
  - /dataset/sources@sources.science_qa_hard_neg_no_cot: science_qa_hard_neg_no_cot
  - /dataset/sources@sources.diverse_qa_hard_neg_no_cot: diverse_qa_hard_neg_no_cot
  - /dataset/sources@sources.multihop_qa_sft: multihop_qa_sft
  - _self_

name: "qa"
seq_len: 512
doc_chunk_seq_len: 256
batch_size: 16
shuffle: true
chat_template: true
provide_docs: true
mask_prefix: true
num_chunks_per_doc: 16
split: train
num_workers: 16
distill: false


