
uv run python single_embedding_retrieval.py \
    --doc_dataset "vm2825/nemotron-cc-v21-Parsed-QA4-filtered-1.7B-evensplit-RQ-8B-parts-0-1-2" \
    --doc_split "train" \
    --doc_column "pos_doc" \
    --max_docs 100000 \
    --query_dataset "vm2825/nemotron-cc-v21-Parsed-QA4-filtered-1.7B-evensplit-RQ-8B-parts-0-1-2" \
    --query_split "train" \
    --query_column "synthetic_question" \
    --query_gt_column "pos_doc" \
    --query_answer_column "answer" \
    --model_name "Qwen/Qwen3-Embedding-0.6B" \
    --hf_ckpt_dir "~/weights/huggingface" \
    --tp_devices 1 \
    --doc_prefix "" \
    --query_task "Given a web search query, retrieve relevant passages that answer the query" \
    --max_doc_length 1024 \
    --max_query_length 128 \
    --encode_batch_size 2048 \
    --search_batch_size 2048 \
    --top_k 10 \
    --num_queries 5000 \
    --embeddings_dir ./embeddings_cache \
    --output results.json
