hf_name: "ragrawal36/nemotron-cc-v2-Parsed-DQA1-answered-1.7B-parts-0-1-2-3"
field_map: {"answer": "synthetic_answer"}
think_field: "think"
teacher_prompt_path: null
student_prompt_path: null
prompt_path: null
